### ISSUE TITLE
HTTP 500 à partir de la page 269

### ISSUE THREAD

**Issue by tusbar** [etalab/geo.data.gouv.fr#408]
```js
MongoError: Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.
    at Function.MongoError.create (/srv/apps/geogw/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/srv/apps/geogw/node_modules/mongoose/node_modules/mongodb-core/lib/cursor.js:212:36)
    at /srv/apps/geogw/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```

=> http://localhost:3000/search?availability=yes&p=269

**Comment by tusbar** [comment]
Fixed by https://github.com/geodatagouv/geoplatform/pull/98
