### ISSUE TITLE
impossible de se logger sur geo.data.gouv.fr

### ISSUE THREAD

**Issue by mkazmiers** [etalab/geo.data.gouv.fr#596]
Bonjour,
pb de d'authentification de data.gouv à geo.data.gouv?

1. Je suis loggé à data.gouv.fr
2. J'essaie d'accéder au dashboard de publication de geo.data.gouv.fr, via "Publier des données" 
3. https://www.data.gouv.fr/fr/oauth/authorize?scope=default&redirect_uri=https%3A%2F%2Fgeo.data.gouv.fr%2Fdgv%2Foauth%2Fcallback&response_type=code&client_id=54ca09cd3ef675ad7d38a33d
![image](https://user-images.githubusercontent.com/16324693/37455243-ec2353ee-283c-11e8-9b68-ada38f73ebe5.png)
4. J'accepte
5. Msg d'erreur sur l'URL suivante : https://geo.data.gouv.fr/dgv/oauth/callback?error=invalid_scope&error_description=The+requested+scope+is+invalid%2C+unknown%2C+or+malformed.
`AuthorizationError: The requested scope is invalid, unknown, or malformed.
   at OAuth2Strategy.authenticate (/srv/apps/geogw/node_modules/passport-oauth2/lib/strategy.js:131:25)
   at attempt (/srv/apps/geogw/node_modules/passport/lib/middleware/authenticate.js:341:16)
   at authenticate (/srv/apps/geogw/node_modules/passport/lib/middleware/authenticate.js:342:7)
   at /srv/apps/geogw/plugins/publish-to-udata/app.js:55:11
   at Layer.handle [as handle_request] (/srv/apps/geogw/node_modules/express/lib/router/layer.js:95:5)
   at next (/srv/apps/geogw/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/srv/apps/geogw/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/srv/apps/geogw/node_modules/express/lib/router/layer.js:95:5)
   at /srv/apps/geogw/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/srv/apps/geogw/node_modules/express/lib/router/index.js:330:12)
   at next (/srv/apps/geogw/node_modules/express/lib/router/index.js:271:10)
   at SessionStrategy.strategy.pass (/srv/apps/geogw/node_modules/passport/lib/middleware/authenticate.js:318:9)
   at SessionStrategy.authenticate (/srv/apps/geogw/node_modules/passport/lib/strategies/session.js:67:10)
   at attempt (/srv/apps/geogw/node_modules/passport/lib/middleware/authenticate.js:341:16)
   at authenticate (/srv/apps/geogw/node_modules/passport/lib/middleware/authenticate.js:342:7)
   at Layer.handle [as handle_request] (/srv/apps/geogw/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/srv/apps/geogw/node_modules/express/lib/router/index.js:312:13)
   at /srv/apps/geogw/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/srv/apps/geogw/node_modules/express/lib/router/index.js:330:12)
   at next (/srv/apps/geogw/node_modules/express/lib/router/index.js:271:10)
   at initialize (/srv/apps/geogw/node_modules/passport/lib/middleware/initialize.js:62:5)
   at Layer.handle [as handle_request] (/srv/apps/geogw/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/srv/apps/geogw/node_modules/express/lib/router/index.js:312:13)
   at /srv/apps/geogw/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/srv/apps/geogw/node_modules/express/lib/router/index.js:330:12)
   at next (/srv/apps/geogw/node_modules/express/lib/router/index.js:271:10)
   at /srv/apps/geogw/node_modules/express-session/index.js:473:7
   at tryCatcher (/srv/apps/geogw/node_modules/bluebird/js/release/util.js:16:23) `

**Comment by noirbizarre** [comment]
Bonjour,

Merci pour votre retour. Nous avons bien identifié et corrigé le problème (cf. opendatateam/udata#1506).

Nous mettons tout en oeuvre pour déployer ce correctif au plus vite

**Comment by jdesboeufs** [comment]
Corrigé en production depuis hier.
