### ISSUE TITLE
Pb de Connexion à geo.data

### ISSUE THREAD

**Issue by jerbou** [etalab/geo.data.gouv.fr#599]
Bonjour,

En me conectant à geo.data, l'erreur suivante a été retourné : 

TokenError: Invalid "code" in request.
   at OAuth2Strategy.parseErrorResponse (/srv/apps/geogw/node_modules/passport-oauth2/lib/strategy.js:320:12)
   at OAuth2Strategy._createOAuthError (/srv/apps/geogw/node_modules/passport-oauth2/lib/strategy.js:367:16)
   at /srv/apps/geogw/node_modules/passport-oauth2/lib/strategy.js:166:45
   at /srv/apps/geogw/node_modules/oauth/lib/oauth2.js:177:18
   at passBackControl (/srv/apps/geogw/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/srv/apps/geogw/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:111:20)
   at IncomingMessage.emit (events.js:208:7)
   at endReadableNT (_stream_readable.js:1064:12)
   at _combinedTickCallback (internal/process/next_tick.js:138:11)
   at process._tickDomainCallback (internal/process/next_tick.js:218:9) 

Est-ce que c'est un message temporaire lié au compte que j'utilise ou pas ?

D'avance Merci,

**Comment by jdesboeufs** [comment]
Merci du signalement on va regarder.

#596

**Comment by jdesboeufs** [comment]
Corrigé
